# Generated by Django 5.0.4 on 2024-04-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={'verbose_name_plural': '3. Startups'},
        ),
        migrations.AlterModelOptions(
            name='startuptype',
            options={'verbose_name_plural': '1. Start up types'},
        ),
    ]
